## find user by id
GET http://localhost:3000/user/370f50a7-c4d0-4c34-b3f7-63f19e432171

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "Isabela Reis Fontele",
    "email": "belafontele1@gmail.com",
    "password": "1234567"
}