### signin user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "belafontenele1@gmail.com",
    "password": "1234567"
}

### signup user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Nicholas Serencovich Fontele",
    "email": "nicholassc2008@gmail.com",
    "password": "1234567"
}

### signout user
POST http://localhost:3000/auth/signout

### who am i
GET http://localhost:3000/auth/whoami